---
config:
  theme: base
  fontSize: 30px
  layout: fixed
---
flowchart TD
 subgraph subGraph0["User Access Layer"]
    direction LR
        Amplify("AWS Amplify Hosting")
        Users("Users / Devices")
  end
 subgraph subGraph1["Auth Layer"]
    direction TB
        Cognito("Amazon Cognito - User Mgmt")
        LambdaAuth("Lambda: Custom Authorizer")
  end
 subgraph subGraph2["Backend Logic - AWS Lambda"]
    direction TB
        LambdaOrders("Lambda: Order Management CRUD")
        LambdaSaleData("Lambda: Sale data processing")
        LambdaPayment("Lambda: Payment Process")
        DynamoDB[("Amazon DynamoDB")]
  end
 subgraph subGraph3["Data Storage & Analytics"]
    direction TB
        S3_Product[("S3: Product Bucket/Media")]
        S3_Analytics[("S3: Analytics Bucket")]
        Athena("Amazon Athena")
        QuickSight("Amazon QuickSight")
  end
    Users --> Amplify
    Amplify -- Handles Auth With --> Cognito
    LambdaAuth -- Validates Identity Info From --> Cognito
    Amplify -- Calls Function --> LambdaOrders
    LambdaOrders -- protected by --> LambdaAuth
    LambdaOrders --> LambdaSaleData
    LambdaSaleData --> DynamoDB
    LambdaPayment --> DynamoDB
    Amplify -- Accesses/Serves --> S3_Product
    DynamoDB -- Export --> S3_Analytics
    S3_Analytics -- Queried By --> Athena
    Athena -- Data Source For --> QuickSight
     Amplify:::awsService
     Cognito:::awsService
     LambdaAuth:::awsService
     LambdaOrders:::awsService
     LambdaSaleData:::awsService
     LambdaPayment:::awsService
     DynamoDB:::awsService
     S3_Product:::awsService
     S3_Analytics:::awsService
     Athena:::awsService
     QuickSight:::awsService
    classDef awsService fill:#FF9900,color:#fff,stroke:#333,stroke-width:1px
