AWSTemplateFormatVersion: '2010-09-09'
Description: >-
  (SHOWCASE ONLY - NO API GATEWAY) CloudFormation template based on the 'Intro' text,
  defining backend resources WITHOUT API Gateway. Includes Lambda (placeholders),
  DynamoDB, and Cognito. Lambdas have NO triggers defined in this template.

Parameters:
  ProjectName:
    Type: String
    Default: SimpleBackendResources
    Description: A prefix for resource names to ensure uniqueness and grouping.

Resources:
  # --- DynamoDB Tables ---
  CustomersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-Customers'
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  OrdersTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-Orders'
      AttributeDefinitions:
        - AttributeName: orderId
          AttributeType: S
        - AttributeName: userId
          AttributeType: S
      KeySchema:
        - AttributeName: orderId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: UserOrdersIndex
          KeySchema:
            - AttributeName: userId
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  FeedbackTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub '${ProjectName}-Feedback'
      AttributeDefinitions:
        - AttributeName: feedbackId
          AttributeType: S
      KeySchema:
        - AttributeName: feedbackId
          KeyType: HASH
      BillingMode: PAY_PER_REQUEST
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # --- Cognito User Pool ---
  UserPool:
    Type: AWS::Cognito::UserPool
    Properties:
      UserPoolName: !Sub '${ProjectName}-UserPool'
      Schema:
        - Name: email
          AttributeDataType: String
          Mutable: true
          Required: true
      Policies:
        PasswordPolicy:
          MinimumLength: 8
      AutoVerifiedAttributes: [email]
      UsernameAttributes: [email]

  UserPoolClient:
    Type: AWS::Cognito::UserPoolClient
    Properties:
      ClientName: !Sub '${ProjectName}-WebAppClient'
      UserPoolId: !Ref UserPool
      GenerateSecret: false
      ExplicitAuthFlows:
        - ALLOW_USER_SRP_AUTH
        - ALLOW_REFRESH_TOKEN_AUTH
      PreventUserExistenceErrors: ENABLED

  # --- IAM Role for Lambda ---
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub '${ProjectName}-LambdaExecutionRole-Basic'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: !Sub '${ProjectName}-LambdaDynamoDBPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:GetItem
                  - dynamodb:PutItem
                  - dynamodb:UpdateItem
                  - dynamodb:DeleteItem
                  - dynamodb:Query
                  - dynamodb:Scan
                Resource:
                  - !GetAtt CustomersTable.Arn
                  - !GetAtt OrdersTable.Arn
                  - !Sub '${OrdersTable.Arn}/index/*'
                  - !GetAtt FeedbackTable.Arn
        - PolicyName: !Sub '${ProjectName}-LambdaCognitoPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - cognito-idp:AdminGetUser
                  - cognito-idp:AdminInitiateAuth
                  - cognito-idp:AdminRespondToAuthChallenge
                  - cognito-idp:SignUp
                  - cognito-idp:ConfirmSignUp
                Resource: !GetAtt UserPool.Arn
        - PolicyName: !Sub '${ProjectName}-LambdaCloudWatchPolicy'
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                Resource: 'arn:aws:logs:*:*:*'
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  # --- Lambda Functions (inline code) ---
  RegisterUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-RegisterUser'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))

              # Example accessing env vars (uncomment if needed)
              # customers_table = os.environ.get('CUSTOMERS_TABLE_NAME')

              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
          CUSTOMERS_TABLE_NAME: !Ref CustomersTable
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  LoginUserFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-LoginUser'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          COGNITO_USER_POOL_ID: !Ref UserPool
          COGNITO_CLIENT_ID: !Ref UserPoolClient
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  CreateOrderFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-CreateOrder'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  GetOrdersFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-GetOrders'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
          ORDERS_INDEX_NAME: UserOrdersIndex
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  GetOrderDetailsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-GetOrderDetails'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  SubmitFeedbackFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-SubmitFeedback'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          FEEDBACK_TABLE_NAME: !Ref FeedbackTable
      Timeout: 10
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

  GetAnalyticsFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${ProjectName}-GetAnalytics'
      Handler: index.lambda_handler
      Runtime: python3.11
      Role: !GetAtt LambdaExecutionRole.Arn
      Code:
        ZipFile: |
          import json
          import os
          import logging

          logger = logging.getLogger()
          logger.setLevel(logging.INFO)

          def lambda_handler(event, context):
              function_name = context.function_name
              logger.info(f"Placeholder function '{function_name}' invoked.")
              logger.info("Received event: " + json.dumps(event, indent=2))
              return {
                  'statusCode': 200,
                  'body': json.dumps({
                      'message': f'Placeholder success from {function_name}',
                      'received_event': event
                  })
              }
      Environment:
        Variables:
          ORDERS_TABLE_NAME: !Ref OrdersTable
          CUSTOMERS_TABLE_NAME: !Ref CustomersTable
      Timeout: 20
      MemorySize: 128
      Tags:
        - Key: Project
          Value: !Ref ProjectName

Outputs:
  CognitoUserPoolId:
    Description: ID of the Cognito User Pool created
    Value: !Ref UserPool
  CognitoUserPoolClientId:
    Description: ID of the Cognito User Pool Client created
    Value: !Ref UserPoolClient
  CustomersTableName:
    Description: Name of the DynamoDB table for Customers
    Value: !Ref CustomersTable
  OrdersTableName:
    Description: Name of the DynamoDB table for Orders
    Value: !Ref OrdersTable
  FeedbackTableName:
    Description: Name of the DynamoDB table for Feedback
    Value: !Ref FeedbackTable
  LambdaExecutionRoleArn:
    Description: ARN of the basic IAM Role used by Lambda functions
    Value: !GetAtt LambdaExecutionRole.Arn
